---
#ansible-playbook ch-directory-permission.yml
- name: run tasks on all hosts
  hosts: all
  tasks:
    - name: ensure a directory exists
      file:
        path: $HOME/test_directory
        state: directory # absent  # to remove
      
    - name: change directory permissions
      file:
        path: "/home/{{ ansible_user }}/test_directory"
        state: directory 
        owner: root
        group: root 
        mode: 0755
      become: yes