---
#ansible-playbook creating-directory.yml
- name: run tasks on all hosts
  hosts: all
  tasks:
    - name: ensure a directory exists
      file:
        path: $HOME/test_directory
        state: directory # absent  # to remove