---
- name: Deploying LAMP Stack
  hosts: db_server
  become: yes
  tasks:
    - name: installing Apachi server
      yum: name=httpd state=latest

    - name: Start Apache server
      service: name=httpd state=started
      
    - name: İnstalling MariaDB Server
      ansible.builtin.yum:
        name: 
          - mariadb-server
          - mariadb-devel
          - mariadb-connectot-odbc
          - mariadb-server-utils
          - python3-PyMySQL
          - php
        state: latest

    - name: start MariaDB Server Service
      service: name=mariadb state=started

    - name: Update MariaDB Server root password
      mysql_user:
        name: root
        host: web_server
        password: mtn
        login_user: root
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"

    - name: Create a new database called İnventory
      mysql_db: name=inventory state=present login_user=root login_password=mtn

    - name: copy SQL file 
      copy: src=/source/servers.sql dest=~/tmp/

    - name: Crate Table called servers with data 
      shell: mysql -u root -pmtn inventory < /tmp/servers.sql

    - name: copy PHP files
      copy: src=/source/connection.php dest=/var/www/html/

    - name: copy index.php file
      copy: src=/source/index.php dest=/var/www/html/

    - name: Restart web service
      service: name=httpd state=restarted
...
