---
- hosts: web_server
  user: ansible
  become: True
  tasks:
    - name: Set MySQL root Password
      mysql_user:
          login_host: ec2-user
          login_user: root
          login_password: ''
          name: root
          
          password: '{{ mysql_pass }}'
          state: present
